### ISSUE TITLE
Latex doesn't render correctly

### ISSUE THREAD

**Issue by johnryan465** [Simpleyyt/jekyll-editor#2]
Latex will not render correctly when inserted $$<--latex-->$$, however Latex renders correctly in Editor.md. An example can be seen on the live demo here https://pandao.github.io/editor.md/en.html . Has some change been made that prevents this from working?

**Comment by Simpleyyt** [comment]
Oh, sorry. I know little about Latex. What is different between Editor.md and Jekyll Editor when inserted $$<--latex-->$$ ? (Sorry, I don't know what $$<--latex-->$$ actually do.)

**Comment by johnryan465** [comment]
Fixed in https://github.com/Simpleyyt/jekyll-editor/commit/ec98472533e988a3d2814bd472e406fc23ac2f66
